### ISSUE TITLE
Add Multiple Clusters

### ISSUE THREAD

**Issue by Smithx10** [jippi/hashi-ui#313] opened 2017-09-13 12:59 UTC
Add the ability to have multiple Consul Clusters and Nomad Clusters. 

For Example: 

CONSUL_ADDR: [ '10.10.10.10:8500', '20.20.20.20:8500' ] .

This would allow for me to view all my different consul clusters in 1 view.

**Comment by jippi** [comment] 2017-09-13 14:08
Closing as duplicate of #210 

I don't think it's worth the complexity to add multiple clusters, rather than having hashi-ui running inside each cluster.

There usually are / should be network ACL preventing cluster cross-talk, and the resources needed to run hashi-ui is so low.

**Closed by jippi** 2017-09-13 14:08 UTC
