### ISSUE TITLE
log fetching interface

### ISSUE THREAD

**Issue by alxark** [jippi/hashi-ui#298] opened 2017-08-27 17:54 UTC
Hello again and thanks again. I've got another proposal for this amazing app. I'm searching for method to keep all nomad jobs logs on separate host and store them to ELK stack via syslog. Currently there is no method to integrate ELK with hashi-ui. I would like to see
API to integrate 3rd party log sources via WebSockets system or something like that. I think it's not a problem to create small daemons to stream info from ES or any other log storage. It should be implemented as additional link to service in consul.

**Comment by jippi** [comment] 2017-08-28 12:37
Duplicate of #188

**Closed by jippi** 2017-08-28 12:37 UTC
