### ISSUE TITLE
NullRef in ClusterEvents.js - impacting /cluster pageload

### ISSUE THREAD

**Issue by snuziale** [jippi/hashi-ui#397] opened 2018-05-22 04:46 UTC
TypeError: Cannot read property 'reverse' of null
    at ClusterEvents.js:25
    at Array.forEach (<anonymous>)
    at ClusterEvents.js:24
    at Array.forEach (<anonymous>)
    at t.value (ClusterEvents.js:22)
    at u (react-dom.production.min.js:130)
    at beginWork (react-dom.production.min.js:133)
    at r (react-dom.production.min.js:161)
    at i (react-dom.production.min.js:161)
    at a (react-dom.production.min.js:162)

ClusterEvents.js
Culprit: allocation.TaskStates[task].Events.reverse().forEach(event => {

```
if (allocation.TaskStates[task].Events) {
...
}
```

**Comment by ramSeraph** [comment] 2018-06-04 08:55
duplicate of #396

**Comment by jippi** [comment] 2018-06-04 09:03
closing as duplicate of #396

**Closed by jippi** 2018-06-04 09:03 UTC
