### ISSUE TITLE
Client list takes a long time to load since updating to v0.20

### ISSUE THREAD

**Issue by mlehner616** [jippi/hashi-ui#349] opened 2017-09-29 20:19 UTC
Current version: v0.21.2

The client page takes an unusually long time to load since updating to v0.20. The client list eventually and consistently loads after ~30 seconds.

<img width="949" alt="screen shot 2017-09-29 at 1 15 02 pm" src="https://user-images.githubusercontent.com/689476/31034287-41701d12-a518-11e7-80e1-67a1b6dffd9e.png">

**Comment by jippi** [comment] 2017-09-29 20:34
How many clients do you have in your cluster?

**Comment by mlehner616** [comment] 2017-10-02 16:11
Hi @jippi: Thank you for the hard work you put into this UI by the way. It's both super useful and super helpful! 

Re: Question - 7 in one cluster and 9 in another

**Comment by mlehner616** [comment] 2017-10-02 16:15
I'm sure this varies by cluster size but what's the CPU/memory requirement you would recommend for a small cluster like this? I'm starting to think the new CPU/memory stats graphs need more CPU/Mem than I have allocated.

Current Allocation:
            "CPU": 600,
            "MemoryMB": 512,

**Comment by jippi** [comment] 2017-10-02 16:38
CPU, depending on cluster size could be 600-5000 MHz (peak) - if it's docker, then CPU is soft limit, so can exceed in bursts just fine. 

Memory I use 128M for hashi-ui, with somewhat stable usage around 22-50MB

**Comment by mlehner616** [comment] 2017-10-07 00:46
debug logs with calls to client endpoint: 
https://gist.github.com/mlehner616/18fe1833054a870aaed91f5eba260a4a

**Comment by mlehner616** [comment] 2017-10-14 01:27
Just a ping on this. It's almost unbearable to wait 30 seconds to view a log for each allocation. Do you have any feedback on this issue?

**Comment by hsmade** [comment] 2017-10-14 05:59
I have to say I don't have that problem. Is this for the log files on the
allocation info page? What happens if you use the nomad CLI to ask for the
logs (nomad logs <alloc-id>)?

**Comment by mlehner616** [comment] 2017-10-14 16:47
Thanks for the reply. nomad client list and nomad logs on the cli is instant.

**Comment by jippi** [comment] 2017-10-15 08:29
@mlehner616 do it still happen in master/latest? i need some debug logs from hashi-ui to even start guessing why

**Comment by jippi** [comment] 2017-10-19 20:04
I'm pretty sure the issue is that hashi-ui can't talk to some clients in your cluster, and thus it takes 30s for the connection to time out :) 

This fix is blocked by https://github.com/hashicorp/nomad/issues/3422

**Comment by mlehner616** [comment] 2017-10-19 20:28
This makes sense. In this particular cluster I am testing out failure scenarios pretty aggressively. So while there are not really that many active nodes (~10) there many many "failed" nodes or "left" nodes.

**Comment by jippi** [comment] 2017-10-19 20:41
failed and left are not attempted a connection at all, so shouldn't be those

**Comment by jippi** [comment] 2018-07-02 19:38
closing, stalled and couldn't reproduce

**Closed by jippi** 2018-07-02 19:38 UTC
Labels: bug
